---
- hosts: "{{ HOSTS is defined | ternary(HOSTS, PREFIX|default('')+'*') }}"
  connection: local
  gather_facts: no
  vars:
    login: &login
      server_url: "https://{{ lookup('env', 'FOREMAN_SERVER') }}"
      username: "{{ lookup('env', 'FOREMAN_USER') }}"
      password: "{{ lookup('env', 'FOREMAN_PASSWORD') }}"
      validate_certs: no
      organization: undef

  tasks:
  - name: destroy cloud instance
    ec2:
      state: absent
      region: "{{ ec2_region }}"
      wait: yes
      instance_ids: "{{ ec2_id }}"

  - name: delete host from satellite
    redhat.satellite.host:
      <<: *login
      name: "{{ inventory_hostname }}"
      state: absent