---
- hosts: "env_{{ server_type }}"
  vars:
    check_only: yes

  tasks:
  - name: check operating system
    assert:
      that: "ansible_os_family == 'RedHat'"

  - name: check for updates
    yum:
      name: '*'
      state: latest
      exclude: kernel*
    check_mode: "{{ check_only }}"
    register: updates
    
  - name: updated package list
    debug:
      msg: "{% if item[0] in  packages %}{{ pacages[item[0]].version }}-{{ pacages[item[0]].release }}.{{ pacages[item[0]].arch }} >>> {{ item[1] }} {% else %} {{ item[1] }} {% endif %}"
    loop: "{{ updates.changes.updated }}"
    loop_control:
      label: "{{ item[0] }}"